ARG SHARE_TAG
# Utilizar la imagen base oficial de Alfresco Share
# FROM alfresco/alfresco-share:${SHARE_TAG}
# FROM alfresco/alfresco-share:23.3.0
FROM alfresco/alfresco-governance-share-community:${SHARE_TAG}
# FROM alfresco/alfresco-governance-share-community:23.4.0

ARG TOMCAT_DIR=/usr/local/tomcat

# Copiar el archivo de configuración al contenedor
#COPY config/share-config-custom.xml /usr/local/tomcat/shared/classes/alfresco/web-extension/share-config-custom.xml

# Server data
ARG SERVER_NAME


# Install modules and addons
# RUN mkdir -p $TOMCAT_DIR/amps
# COPY modules/amps $TOMCAT_DIR/amps
# COPY modules/jars $TOMCAT_DIR/webapps/share/WEB-INF/lib

# RUN java -jar $TOMCAT_DIR/alfresco-mmt/alfresco-mmt*.jar install \
#     $TOMCAT_DIR/amps $TOMCAT_DIR/webapps/share -directory -nobackup -force

# Increase default cacheMaxSize
RUN sed -i "s|<Context>|<Context>\n<Resources cacheMaxSize=\"51200\"/> |g" $TOMCAT_DIR/conf/context.xml

# Fix for https://github.com/Alfresco/acs-community-packaging/issues/367 in Share 6.2.0
COPY web-extension/share-config-custom-dev.xml $TOMCAT_DIR/shared/classes/alfresco/web-extension/

# Exponer el puerto en el que Alfresco Share escucha
# EXPOSE 9090

#Iniciar el servidor de Tomcat
#CMD ["catalina.sh", "run"]
